config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :buckets
  resources :wishlists
  get 'pages/info'
  post 'rate' => 'products#rate'
  post 'addtobucket' => 'buckets#addtobucket'
  post 'deletebucket' => 'buckets#deletebucket'
  post 'addtowishlist' => 'wishlists#addtowishlist'
  post 'deletewishlist' => 'wishlists#deletewishlist'
  post 'compare' => 'wishlists#compare'
  post 'delcompare' => 'wishlists#delcompare'
	root to: 'ewlcome#index'
	devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_for :users
  resources :comments
  resources :products
  post 'checkout' => 'orders#checkout'
  get 'payment/:id' => 'orders#payment'
  get 'payment/create2/:id' => 'orders#create2'
  get 'administration' => 'wishlists#administration'
  get 'adm_search' => 'wishlists#adm_search'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bucket.rb
class Bucket < ApplicationRecord
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  before_action :set_bucket, only: [:show, :edit, :update, :destroy]

  # GET /buckets
  # GET /buckets.json
  def index
    if Bucket.find_by(user_id: current_user.id).present?
      @buckets = []
      @a = Bucket.find_by(user_id: current_user.id)
      @a.product_id.each do |b|
        if Product.exists?(id: b[0])
          c = Product.find(b[0])
          @buckets << c
        else
          b = nil
        end
      end
      @a.product_id = @a.product_id.compact
      @a.save
      @buckets
      @a
    end
  end

  def addtobucket
    if Bucket.find_by(user_id: current_user.id).present?
      a = Bucket.find_by(user_id: current_user.id)
      b = false
      a.product_id.each do |x|
        if x[0] == params['product_id'].to_i
          x[1] = x[1] + 1
          b = true
        end
      end
      if b == false
        a.product_id << [params['product_id'],1]
      end
      a.save
      if params[:number].to_i == 1
        redirect_to request.referrer
      end
    else
      a = Bucket.new(user_id: current_user.id, product_id: [[params['product_id'],1]])
      a.save
      if params[:number].to_i == 1
        redirect_to request.referrer
      end
    end

  end

  def deletebucket
    a = Bucket.find_by(user_id: current_user.id)
    b = 0
    c = nil
    a.product_id.each do |x|
      if x[0] == params[:product_id].to_i
        x[1] = x[1] - params[:number].to_i
      end
      if x[1] <= 0
        c = b
      end
      b = b + 1
    end
    if c != nil
      a.product_id.delete_at(c)
    end
    a.save
    redirect_to request.referrer
  end
  # GET /buckets/1
  # GET /buckets/1.json
  def show
  end

  # GET /buckets/new
  def new
    @bucket = Bucket.new
  end

  # GET /buckets/1/edit
  def edit
  end

  # POST /buckets
  # POST /buckets.json
  def create
    @bucket = Bucket.new(bucket_params)

    respond_to do |format|
      if @bucket.save
        format.html { redirect_to @bucket, notice: 'Bucket was successfully created.' }
        format.json { render :show, status: :created, location: @bucket }
      else
        format.html { render :new }
        format.json { render json: @bucket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buckets/1
  # PATCH/PUT /buckets/1.json
  def update
    respond_to do |format|
      if @bucket.update(bucket_params)
        format.html { redirect_to @bucket, notice: 'Bucket was successfully updated.' }
        format.json { render :show, status: :ok, location: @bucket }
      else
        format.html { render :edit }
        format.json { render json: @bucket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buckets/1
  # DELETE /buckets/1.json
  def destroy
    @bucket.destroy
    respond_to do |format|
      format.html { redirect_to buckets_url, notice: 'Bucket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bucket
      @bucket = Bucket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bucket_params
      params.permit(:user_id, :product_id, :number)
    end
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/views/buckets/_form.html.erb
<%= form_with(model: bucket, local: true) do |form| %>
  <% if bucket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bucket.errors.count, "error") %> prohibited this bucket from being saved:</h2>

      <ul>
      <% bucket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :bucket_user_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id, id: :bucket_product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buckets/edit.html.erb
<h1>Editing Bucket</h1>

<%= render 'form', bucket: @bucket %>

<%= link_to 'Show', @bucket %> |
<%= link_to 'Back', buckets_path %>

app/views/buckets/index.html.erb
<div class="conteiner-bucket">
  <% if @buckets.present? %>
    <%= link_to 'finnish your order', new_order_url, class: "waves-effect waves-light btn", style: "float:right;margin-left:30px;" %>
  <% end %>
  <h1>Your bucket</h1>
  <hr class="my-4">
  <% if !@buckets.present? %>
    <h3> Your bucket is empty </h3>
  <% else %>
  <div class="bucket-table col s8 offset-s2" >
    <table>
      <thead>
        <tr>
          <th>Products</th>
          <th>Quantity</th>
          <th>Unit price</th>
          <th>Amount</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% b = 0 %>
        <% @buckets.each do |bucket| %>
          <tr>
            <td><%= link_to "#{bucket.title}", product_url(bucket) %></td> 
            <% z = 0 %>
            <% @a.product_id.each do |x| %>
              <% if x[0] == bucket.id %>
                <td>
                  <% if x[1] > 1 %>
                    <%= link_to '-', {:controller => "buckets", :action => "deletebucket", :product_id => bucket.id, :number => 1 }, method: :post, remote: true%>
                  <% else %>
                    &nbsp;
                  <% end %>
                  <%= x[1] %>
                  <%= link_to '+', {:controller => "buckets", :action => "addtobucket", :product_id => bucket.id, :number => 1}, method: :post, remote: true%>
                  </td>
                <% z = x[1] %>
              <% end %>
            <% end %>
            <td><%= bucket.price %></td> 
            <td><%= bucket.price * z %></td> 
            <td><%= link_to 'delete', {:controller => "buckets", :action => "deletebucket", :product_id => bucket.id, :number => z }, method: :post, remote: true, :data => {:confirm => 'are you sure?'} %></td>
            <% b = b+(bucket.price*z) %>
          </tr>
        <% end %>
        <td>Total price: &nbsp; <%=b%></td>
      </tbody>
    </table>
  </div>
 <% end %>
</div>

app/views/buckets/new.html.erb
<h1>New Bucket</h1>

<%= render 'form', bucket: @bucket %>

<%= link_to 'Back', buckets_path %>

app/views/buckets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @bucket.user_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @bucket.product_id %>
</p>

<%= link_to 'Edit', edit_bucket_path(@bucket) %> |
<%= link_to 'Back', buckets_path %>