config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :buckets
  resources :wishlists
  get 'pages/info'
  post 'rate' => 'products#rate'
  post 'addtobucket' => 'buckets#addtobucket'
  post 'deletebucket' => 'buckets#deletebucket'
  post 'addtowishlist' => 'wishlists#addtowishlist'
  post 'deletewishlist' => 'wishlists#deletewishlist'
  post 'compare' => 'wishlists#compare'
  post 'delcompare' => 'wishlists#delcompare'
	root to: 'ewlcome#index'
	devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_for :users
  resources :comments
  resources :products
  post 'checkout' => 'orders#checkout'
  get 'payment/:id' => 'orders#payment'
  get 'payment/create2/:id' => 'orders#create2'
  get 'administration' => 'wishlists#administration'
  get 'adm_search' => 'wishlists#adm_search'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	# has_many :comments
	# has_many :pictures, dependent: :destroy



	def self.search(term)
  		if term
    		where('title LIKE ?', "%#{term}%")
  		else
    		all
  		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]

  # GET /products
  # GET /products.json
  def index
    @wish = Wishlist.where("user_id = ?", current_user.id).first
    @categoryes = Categorye.all
    if params[:category].present?
      @products = Product.where(category: params[:category])
    else
      @products = Product.search(params[:term])
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    if !current_user.admin
      @product.statistic = @product.statistic + 1
      @product.save
    end
    @wish = Wishlist.where("user_id = ?", current_user.id).first
    @comments = Comment.where(product_id: @product.id).order(:created_at)    
  end

  # GET /products/new
  def new
    if current_user.admin?
      @product = Product.new
    else
      redirect_to root_path
    end
  end

  def rate
    @a = Product.find(params[:product_id].to_i)
    @a.rate_user << current_user.id
    @a.rating << params[:rating].to_i
    @a.save
    respond_to do |f|
      f.html { render @a }
      f.js
    end
  end

  # GET /products/1/edit
  def edit    
    if current_user.admin?
    else
      redirect_to root_path
    end
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new()
    @product.title = product_params[:title]
    @product.description = product_params[:description]
    @product.stock = product_params[:stock]
    @product.price = product_params[:price]
    @product.category = product_params[:category]
    b = product_params[:images].split(',')
    b.each do |x|
      @product.images << x
    end
    if Categorye.find_by(title: params[:category]).present?
    else
      a = Categorye.new(title: params[:category])
      a.save
    end
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    s3_client = Aws::S3::Client.new
    @product.images.each do |x|
      v = x.split('/')
      v.delete_at(0)
      v.delete_at(0)
      v.delete_at(0)
      z = v.join('/')
      s3_client.delete_object(key: z, bucket: 'enotikbucket')
    end
    @b = @product.id
    @product.destroy
  end

  private


    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_s3_direct_post
      @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :stock, :price, :rating, :product_id, :category, :images)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true, class: "directUpload", data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host}) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description, class: "materialize-textarea" %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :product_category %>
  </div>

  <div class="field">
    
     
  </div>

  <div class="file-field input-field">
    <div class="btn">
      <span>Images</span>
      <%= form.file_field :images, multiple: true%>
    </div>
    <div class="file-path-wrapper">
      <input class="file-path validate" type="text" placeholder="Upload one or more files">
    </div>
  </div>
 
  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.text_field :stock, id: :product_stock %>
  </div>

  <div class="actions">
    <%= form.submit 'apply changes', class: 'waves-effect waves-light btn'%>
  </div>
<% end %><br>

<script type="text/javascript">
    $( document ).ready('turbolinks:load');
     $('.directUpload').find("input:file").each(function(i, elem) {
      var pictures     = [];
      var fileInput    = $(elem);
      var form         = $(fileInput.parents('form:first'));
      var submitButton = form.find('input[type="submit"]');
      var progressBar  = $("<div class='bar'></div>");
      var barContainer = $("<div class='progress'></div>").append(progressBar);
      fileInput.after(barContainer);
      fileInput.fileupload({
        fileInput:       fileInput,
        url:             form.data('url'),
        type:            'POST',
        autoUpload:       true,
        multipart:        true,
        formData:         form.data('form-data'),
        paramName:        'file', // S3 does not like nested name fields i.e. name="user[avatar_url]"
        dataType:         'XML',  // S3 returns XML if success_action_status is set to 201
        replaceFileInput: false,
        progressall: function (e, data) {
          var progress = parseInt(data.loaded / data.total * 100, 10);
          progressBar.css('width', progress + '%')
        },
        start: function (e) {
          submitButton.prop('disabled', true);

          progressBar.
            css('background', 'green').
            css('display', 'block').
            css('width', '0%').
            text("Loading...");
        },
        done: function(e, data) {
          submitButton.prop('disabled', false);
          progressBar.text("Uploading done");

          // extract key and generate URL from response
          var key   = $(data.jqXHR.responseXML).find("Key").text();
          var url   = '//' + form.data('host') + '/' + key;
          pictures.push(url)
          var a = pictures.join(',');
          var input = $("<input />", { class: 'to_save', type:'hidden', name: 'product[images]', value: a})
          $('.to_save').remove();
          $('.directUpload').append(input);
          // create hidden field
        },
        fail: function(e, data) {
          submitButton.prop('disabled', false);

          progressBar.
            css("background", "red").
            text("Failed");
        }
      });
    });
</script>

app/views/products/destroy.js.erb
$('#prod_card_<%=@b%>').remove();

app/views/products/edit.html.erb
<div style="margin: 20px;">
	<h1>Editing Product</h1>

	<%= render 'form', product: @product %>

	<%= link_to 'Show', @product %> |
	<%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="bla">
    <%= form_tag(products_path, method: :get) do %>
      <%= text_field_tag :term,  params[:term] %>
      <%= button_tag(type: "submit", class: "waves-effect waves-light btn search_line") do %>
        <i class="material-icons">search</i>
      <% end %> 
    <% end %>
  </div>

  <div class="row">
    <% @products.each do |product| %>
      <div class="col s6 m4" id="prod_card_<%=product.id%>">
        <div class="card">
          <div class="card-image">
            <%= link_to(product) do %>
              <%= image_tag(product.images[0]) if product.images? %>
            <% end %>
            <span class="card-title" style="color: black;"><%= product.title %></span>
          </div>
          <div class="card-content">
            <p><%=product.description%></p>
            <p>Price:&nbsp;<%=product.price%></p>
          </div>
          <div class="card-action">
            <% if current_user.admin %>
              <%= link_to "edit", edit_product_path(product), class: 'waves-effect waves-light btn', data: {turbolinks: false}%>
              <%= link_to(product, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: 'waves-effect waves-light btn', style: 'float:right;') do%><i class="material-icons">delete</i><%end%>
            <% else %>
              <%= link_to({:controller => "buckets", :action => "addtobucket", :product_id => product.id, :number => 0 }, method: :post, remote: true, class: "addtobucket waves-effect waves-light btn", id: "addtobucket"+product.id.to_s) do%><i class="material-icons">add_shopping_cart</i><%end%>
              <% if @wish.present? && @wish.product_id.include?(product.id)%>
                <%= link_to({:controller => "wishlists", :action => "deletewishlist", :product_id => product.id }, method: :post, remote: true, id: "deletewishlist"+product.id.to_s, :data => {:confirm => 'are you sure?'} , style: 'margin: 0 10px;', class: 'waves-effect waves-light btn wishbtn') do%><i class="material-icons">favorite</i><%end%>
              <% else %>
                <%= link_to({:controller => "wishlists", :action => "addtowishlist", :product_id => product.id, :number => 0}, method: :post, remote: true, id: "addtowishlist"+product.id.to_s, style: 'margin: 0 10px;', class: 'waves-effect waves-light btn wishbtn') do%><i class="material-icons">favorite_border</i><%end%>
              <%end%>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>


<script type="text/javascript" integrity="">
 $('.dropdown-button').dropdown();
  $(document).ready(function () {

    $(".addtobucket").on('ajax:success', function(){
      alert("This product was added to bucket");
    });
  });
</script>

app/views/products/new.html.erb
<div style="margin:20px;">
	<h1>New Product</h1>
	<hr class="my-4">
	<%= render 'form', product: @product %>
</div>

app/views/products/rate.js.erb
<% b = @a.rating.inject(0.0) { |sum, el| sum + el } / @a.rating.size %>
$(".rate").remove();
$('#rate3').remove();
	for (i = 1; i < 6; i++){
		if (i <= '<%=b%>'){
			$('.rate1').append('<i class="material-icons ">star</i>');
		}else{
			$('.rate1').append('<i class="material-icons ">star_border</i>');
		};
	};
$('.rate1').append('<p id="rate3" style="text-align: center;">Have rated: <%=@a.rating.size %></p>');

app/views/products/show.html.erb
<div class="conteiner-show" style="margin-top: 50px;">
  <% if current_user.admin %>
    <%= link_to 'Edit', edit_product_path(@product), class: 'waves-effect waves-light btn bla', style: 'float:right;width:200px;', data: {turbolinks: false}%> 
  <% else %>
    <div class="rate1" style="width: 140px;float: left;">
      <% a1 = 1 %>
      <% a2 = @product.rating.inject(0.0) { |sum, el| sum + el } / @product.rating.size %>
      <p id="rate2" bla="<%= a2%>" bla1="<%=@product.rate_user.include?(current_user.id) %>"></p>
      <% a3 = 1 %>
      <% 5.times do %>
        <% if @product.rate_user.include?(current_user.id)%> 
          <% if a1 <= a2 %>
            <i class="material-icons star">star</i>
          <% else %>
            <i class="material-icons star">star_border</i>
          <% end %> 
        <% else %>
          <% if a1 <= a2 %>
            <%= link_to( {:controller => "products", :action => "rate", :product_id => @product.id, :rating => a1 }, method: :post, remote: true, class: 'rate') do%>
              <i class="material-icons star">star</i>
            <% end %>
          <% else %>
            <%= link_to( {:controller => "products", :action => "rate", :product_id => @product.id, :rating => a1 }, method: :post, remote: true, class: 'rate') do%>
                <i class="material-icons star">star_border</i>
            <% end %>
          <% end %>
        <%end%>
        <% a1 = a1+1 %>
      <% end %>
      <p id="rate3" style="text-align: center;">Have rated: <%=@product.rating.size %></p>
    </div>
    <%= link_to({:controller => "buckets", :action => "addtobucket", :product_id => @product.id }, method: :post, remote: true, class: "waves-effect waves-light btn add_to", style: "float:right; margin: 0px 10px;", id: "addtobucket"+@product.id.to_s) do%><i class="material-icons">add_shopping_cart</i><%end%>
    <% if @wish.present? && @wish.product_id.include?(@product.id)%>
      <%= link_to({:controller => "wishlists", :action => "deletewishlist", :product_id => @product.id }, method: :post, class: "waves-effect waves-light btn", remote: true, style: "float:right;margin: 0px 10px;", id: "deletewishlist"+@product.id.to_s, :data => {:confirm => 'are you sure?'}) do%><i class="material-icons">favorite</i><%end%>
    <% else %>
      <%= link_to({:controller => "wishlists", :action => "addtowishlist", :product_id => @product.id, :number => 0}, method: :post, remote: true, style: "float:right;margin: 0px 10px;", class: "waves-effect waves-light btn", id: "addtowishlist"+@product.id.to_s) do%><i class="material-icons">favorite_border</i><%end%>
    <%end%>
    <% if @wish.present? %>
      <% if @wish.compare.size < 4%>
        <% if @wish.compare.include?(@product.id) %>
          <%= link_to 'allready there', {:controller => "wishlists", :action => "compare", :product_id => @product.id, :number => 0}, method: :post, remote: true, class: "waves-effect waves-light btn comp_btn disabled", style: 'margin: 0px 40px;'%>
        <% else %>
          <%= link_to 'compare', {:controller => "wishlists", :action => "compare", :product_id => @product.id, :number => 0}, method: :post, remote: true, class: "waves-effect waves-light btn comp_btn", style: 'margin: 0px 40px;'%>
        <%end%>
      <% else %>
        <%= link_to 'Thats enough', {:controller => "wishlists", :action => "compare", :product_id => @product.id, :number => 0}, method: :post, remote: true, class: "waves-effect waves-light btn comp_btn disabled", style: 'margin: 0px 40px;'%>
      <% end %>
    <%else%>
      <%= link_to 'compare', {:controller => "wishlists", :action => "compare", :product_id => @product.id, :number => 0}, method: :post, remote: true, class: "waves-effect waves-light btn comp_btn", style: 'margin: 0px 40px;'%>
    <%end%>
<% end %>
<h1 style="text-align: center;" id="link-to-comp">
  <%= @product.title %>
</h1>
<hr class="my-4">
<div class="row">
<div class="product-body col s5">
  <% @product.images.each do |image| %>
    <%= image_tag image, style: "width: 50px;height: 50px;", data: {zoom_image: image}, class: 'zoom1'%>
  <% end %><br>
  <p>
    <strong>Description:</strong>
    <%= @product.description %>
  </p>
  <p>
    <strong>Category:</strong>
    <%= @product.category %>
  </p>
  <p>
    <strong>Price:</strong>
    <%= @product.price %>
  </p>
  <p>
    <strong>Stock:</strong>
    <% if @product.stock > 0 %>
      In stock. <%=@product.stock%> left 
    <% else %>
      Out of stock
    <% end %>
  </p>
  <% if current_user.admin %>
    <p>
      <strong>visited:</strong>
      <%= @product.statistic %>
    </p>
    <br>
  <% end %>
</div>
<div class="product-comment col s6 offset-s1">
  <h3 class="com_place">Comments</h3>
  <% @comments.each do |comment| %>
    <div style="margin-bottom: 5px;padding: 10px;" id="comment_<%=comment.id%>"
      class="com_place">
      <strong><%= comment.user_name %>&nbsp;<%=comment.created_at.strftime('%FT%R')%></strong>
      <% if current_user.email == comment.user_name || current_user.admin %>
      <%= link_to 'Delete', comment_path(comment), method: :delete, remote: :true, data: { confirm: 'Are you sure?' }%>
      <% end %>
      <p><%= comment.body %></p>
    </div>
  <% end %><br>
  <p>Leave your awesome comment:</p>
  <%= render 'comments/form',  comment: @comment  %>
  </div>
</div>
</div>

<script type="text/javascript">
  
   // $('.chip').chips();
  $(document).ready(function () {
    $(".add_to").on('ajax:success', function(){
      alert("This product was added to bucket");
    });
    $(document).ready(function(){
       
        $('.card-comp').draggable();
      })
    $(".zoom1").ezPlus();
          $('.rate').mouseenter(function(){
        $(this).prevAll().children().text('star');
        $(this).children().text('star');
      });
      $('.rate').mouseleave(function(){
        $(this).prevAll().children().text('star_border');
        $(this).children().text('star_border');
      });

      $('.rate1').mouseenter(function(){
        if ($('#rate2').attr('bla1') == 'false'){
        $('.rate').children().text("star_border");
      };
      });
      $('.rate1').mouseleave(function(){
        
        if ($('#rate2').attr('bla1') == 'false'){
        var a = 1;
        $('.star').each(function(){
          if (a <= $("#rate2").attr("bla")){
            $(this).text('star');
          }else{
            $(this).text('star_border');
          };
          a = a+1;
        });
      };
      });
  });
</script>