config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :buckets
  resources :wishlists
  get 'pages/info'
  post 'rate' => 'products#rate'
  post 'addtobucket' => 'buckets#addtobucket'
  post 'deletebucket' => 'buckets#deletebucket'
  post 'addtowishlist' => 'wishlists#addtowishlist'
  post 'deletewishlist' => 'wishlists#deletewishlist'
  post 'compare' => 'wishlists#compare'
  post 'delcompare' => 'wishlists#delcompare'
	root to: 'ewlcome#index'
	devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_for :users
  resources :comments
  resources :products
  post 'checkout' => 'orders#checkout'
  get 'payment/:id' => 'orders#payment'
  get 'payment/create2/:id' => 'orders#create2'
  get 'administration' => 'wishlists#administration'
  get 'adm_search' => 'wishlists#adm_search'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bucket.rb
class Bucket < ApplicationRecord
end

app/models/categorye.rb
class Categorye < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
	# belongs_to :product
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/picture.rb
class Picture < ApplicationRecord
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
	# has_many :comments
	# has_many :pictures, dependent: :destroy



	def self.search(term)
  		if term
    		where('title LIKE ?', "%#{term}%")
  		else
    		all
  		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,  :omniauthable, omniauth_providers: %i[facebook]

  def self.from_omniauth(auth)
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    	user.email = auth.info.email
    	user.password = Devise.friendly_token[0,20]
    	user.email = auth.info.email   # assuming the user model has a name
    	# user.image = auth.info.image # assuming the user model has an image
    	# If you are using confirmable and the provider(s) you use validate emails, 
    	# uncomment the line below to skip the confirmation emails.
    	# user.skip_confirmation!
  	end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  require "rubygems"
  require "braintree"

  
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where(user_id: current_user.id)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    
    @product = []
    @order.product_id.each do |z|
      a = Product.find(z[0])
      @product << a
    end
    @product
    @order
  end

  # GET /orders/new
  def new
    @order = Order.new
    @a = []
    x = 0
    @b = Bucket.find_by(user_id: current_user.id)
    @b.product_id.each do |c|
      v = Product.find(c[0])
      x = x + v.price*c[1]
      @a << [v, v.price*c[1], c[1]]
    end
    @a << x
    @a
    @b
    @order
  end

  def checkout
    nonce_from_the_client = params[:payment_method_nonce]
    result = gateway.transaction.sale(
      :amount => "10.00",
      :payment_method_nonce => nonce_from_the_client,
      :options => {
        :submit_for_settlement => true
      }
    )
  end

  # GET /orders/1/edit
  def edit
  end

  def payment
    if Order.exists?(id: params[:id])
      @order = Order.find(params[:id])
      if @order.user_id == current_user.id && @order.complit == false
        gateway = Braintree::Gateway.new(
          :environment => :sandbox,
          :merchant_id => ENV["bt_merchant_id"],
          :public_key => ENV["bt_public_key"],
          :private_key => ENV["bt_private_key"]
        )
        @token = gateway.client_token.generate
      else
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order[:user_id] = current_user.id
    @order.price = params['price']
    a = params["product_id"].split(' ')
    b = a.each_slice(2).to_a
    @order.product_id = b
    @order.save
    respond_to do |format|
      if @order.save
        format.html { redirect_to '/payment/'+@order.id.to_s}
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def create2
    if Order.exists?(id: params[:id])
      @order = Order.find(params[:id])
      @order.product_id.each do |x|
        v = Product.find(x[0].to_i)
        v.stock = v.stock - x[1].to_i
        v.save
      end
      @order.complit = true
      @order.save
      c = Bucket.find_by(user_id: current_user.id)
      c.destroy
      @user = User.find(current_user.id)
      OrderJob.perform_later(@user, @order)
      respond_to do |format|
          format.html { redirect_to root_path, notice: 'Order was successfully finished.' }
          format.json { render :show, status: :ok, location: @order }
      end
    else
      redirect_to root_path
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :complit, :payment_method_nonce, :price, :adress, :product_id => [] )
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ewlcome_helper.rb
module EwlcomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Third</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', integrity: "", media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css" integrity="">
    <%= javascript_include_tag 'application', integrity: "", 'data-turbolinks-track': 'reload' %>
    <script src="https://js.braintreegateway.com/web/dropin/1.9.4/js/dropin.min.js" integrity=""></script>
  </head>
  <body>
  	<% if user_signed_in? %>
  	 <nav style="padding: 3px;">
      <div class="nav-wrapper">
        <%=link_to "The Test app", root_path, class: "brand-logo", integrity: ""%>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <% if @categoryes.present? %>
              <li><a class="dropdown-button btn" href="#" data-activates='dropdown1' tabindex="-4">Categories</a></li>
                <ul id='dropdown1' class='dropdown-content'>
                  <% @categoryes.each do |category| %>
                    <li><%= link_to category.title, {:controller => "products", :action => "index", :category => category.title}, method: :get, integrity: ""%></li>
                  <% end %>
                </ul>
            <% end %>
            <li>Logged in as <strong><%= current_user.email %></strong></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path%></li>
            <% if current_user.admin %>
              <li><%= link_to "Administration", {:controller => "wishlists", :action => "administration"}%></li>
            <% else %>
              <li><%= link_to "Bucket", buckets_url%></li>
              <li><%= link_to "Orders", orders_url%></li>
              <li><%= link_to "Wishlist", wishlists_url%></li>
            <% end %>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, integrity: ""%></li>
        </ul>
      </div>
    </nav>
    <div id="comp1" class="row" >
      <% a = 10 %>
      <% @compare.each do |prod|%>
        <div class='col s2 offset-s<%=a%> card-comp' id='comp2_<%=prod.id%>'>
          <div class='card pink accent-4' style="width: 150px;">
            <div class='card-content white-text'>
              <%=link_to(prod, integrity: "") do %>
                <span class="card-title"><%=prod.title%></span>
              <%end%>
              <p><%=prod.description%></p>
              <p class='card-text'>Price:&nbsp;<%=prod.price%></p>
            </div>
            <div class="card-action">
              <%= link_to 'close', {:controller => "wishlists", :action => "delcompare", :product_id => prod.id, :number => 0}, method: :post, remote: true, integrity: ""%>
            </div>
          </div>
        </div>
        <% a = a - 1 %>
      <% end %> 
    </div>
  	<% else %>
    <% end%>
      <div class="container">
    	  <% if notice %>
  			 <p class="alert alert-success"><%= notice %></p>
		    <% end %>
		    <% if alert %>
  			 <p class="alert alert-danger"><%= alert %></p>
		    <% end %>
	    </div>
    <%= yield %>
    <script
    src="https://code.jquery.com/jquery-3.3.1.js"
    integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js" integrity=""></script>
    <script type="text/javascript" src="https://cdn.rawgit.com/igorlino/elevatezoom-plus/1.1.6/src/jquery.ez-plus.js" integrity=""></script>
      <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" integrity=""></script>

    <script type="text/javascript" integrity="">
      $(document).ready(function(){
        $('.card-comp').draggable();
      })
    </script>
  </body>
</html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>